language: android
sudo: required
android:
  components:
    # some travis/android magic from
    # * https://github.com/travis-ci/travis-ci/issues/5036
    # * https://stackoverflow.com/questions/28751111/invalid-abi-armeabi-v7a-for-the-selected-target-with-google-apis
    - tools
    - platform-tools

    # The BuildTools version used by your project
    - build-tools-28.0.2

    # The SDK version used to compile your project
    - android-26

    # Additional components
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-addon-google_apis-google-26
env:
- GRADLE_OPTS="-XX:MaxPermSize=512m"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_script:
  - export VERSION_TO_BUILD="$TRAVIS_TAG"
  - yes | sdkmanager 'platforms;android-28'
script: make travis
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - build/outputs/apk/medic/release/medic-gateway-${VERSION_TO_BUILD}-medic-release.apk
    - build/outputs/apk/generic/release/medic-gateway-${VERSION_TO_BUILD}-generic-release.apk
  skip_cleanup: true
  on:
    tags: true
